FROM python:3.8-slim-buster
  
WORKDIR /app

#COPY requirements.txt requirements.txt
RUN  pip install kafka-python  requests
COPY client.py client.py
#RUN pip3 install -r requirements.txt

ENTRYPOINT python3 client.py
